### ISSUE TITLE
error 1501 when launching through qclauncher

### ISSUE THREAD

**Issue by Lamieur** [syncore/qclauncher#14] opened 2018-09-07 14:30 UTC
Since yesterday's QC update, launching through Bethesda Launcher works, but if I launch with qclauncher like all real men do, it launches the game but after all the movies play I get error 1501:

![obraz](https://user-images.githubusercontent.com/1531170/45224671-ce52e380-b2ba-11e8-82e7-bfe33694ed8d.png)

Unlike the last time when downgrading helped, this time neither version 1.05 nor 1.04 work :/

I really hope you're still interested enough to keep this project going!

(And thanks again for quick fix the last time!)

**Comment by adem4ik** [comment] 2018-09-08 11:07
just in case, there is a similar problem on Linux under Steam Play's Proton emulator but with `error code 103` - https://github.com/ValveSoftware/Proton/issues/225#issuecomment-419283329

**Comment by Random1984** [comment] 2018-09-08 20:08
I suspect this is related to the new UAC request that pops when launching the game.

**Comment by Lamieur** [comment] 2018-09-10 16:53
There are multiple threads about this, but this is a gem: https://bethesda.net/community/post/1237495

Bethesda Customer Support Team telling people "this is a Windows problem, go bug Microsoft", even though this has been caused by their update for tens of people, and shows a cryptic Bethesda bug number that won't tell Microsoft anything :)

So yeah, this may have to do with that UAC popup before every launch (asking to create a pipe?) Hope that's some form of anti-cheat and not another spyware.

The question remains, is it possible to emulate that without Bethesda.net Launcher.

**Comment by syncore** [comment] 2018-10-11 18:26
I've been gone a while; is there still interest in this?

**Comment by Lamieur** [comment] 2018-10-11 18:59
Sure there is! :)

Also, we hope you had a great time on your vacation from Quake and all!

So I just confirmed:
- Bethesda.net Launcher is still garbage (latest update was supposed to fix constant asking for password - guess what, one reboot later it asked for password and didn't even accept the correct one - as always... (full disclosure: it started before Internet went up; still: it claims my password is not what it has in its cache, but I never ever changed my password, so let's just agree it's absolute shit)
- Error 1501 is still there after QC 2018-10-11 update.

So hell yeah there's still interest! :)

I retract my comment about a pipe, after actually reading that message, the pipe is completely unrelated.

Also, there have been tens of people reporting error 1501 while NOT using qclauncher - no idea what that error is supposed to mean, but there's potentially a huge number of people who would benefit from a launcher that could work around that thing...

**Comment by syncore** [comment] 2018-10-17 06:52
[**This**](https://www.syncore.org/qclauncher-1.06_beta.zip) can be tested from the [fp branch](https://github.com/syncore/qclauncher/tree/fp). It successfully allowed me to authenticate with QC without 1501; however, I've only tested it on one machine (mine). I'd be curious to know if it works for anyone else.

**Comment by Random1984** [comment] 2018-10-17 14:49
Runs fine in Win7 x64.

**Comment by Lamieur** [comment] 2018-10-17 19:23
Worked on my Windows 10. The invisible Beth Launcher restarts while the QCLauncher was (not responding) on the settings screen need at least a small splash saying "gathering data in progress, please stand by" :) Afterwards it just worked, that's what I'm talking about! :)

Does not work on Linux though - copying data.qcl from Windows partition doesn't work (error 1501 still), clearly WINE presents the same hardware differently and that must invalidate that hardware profile that qclauncher is caching. And unfortunately, Bethesda.net Launcher doesn't work in WINE, so there goes one of my two use cases for qclauncher, RIP :(

My Linux fetish aside, people who get error 1501 on actual Windows 10 probably won't benefit from this either, if we're simply extracting that profile from BNL, and then QC expects something else for whatever reason?


(inb4 Steam noobs comment: yes, I know it works from Steam through Proton, but I don't want to convert my main account into a Steam-only one)

**Comment by syncore** [comment] 2018-10-19 05:40
> Worked on my Windows 10. The invisible Beth Launcher restarts while the QCLauncher was (not responding) on the settings screen need at least a small splash saying "gathering data in progress, please stand by"

Yeah, I [anticipated that this could be an issue](https://github.com/syncore/qclauncher/blob/fp/uiwindowsettings.go#L74); need to address it.

> 
> Does not work on Linux though - copying data.qcl from Windows partition doesn't work (error 1501 still), clearly WINE presents the same hardware differently and that must invalidate that hardware profile that qclauncher is caching. And unfortunately, Bethesda.net Launcher doesn't work in WINE, so there goes one of my two use cases for qclauncher, RIP :(

I've confirmed that on start, QC itself also calculates the hardware fingerprint, using the same FP calculation mechanism that BNL does, regardless of whether BNL is open. The values between Windows and Linux (and even between two Windows machines) will not be the same for various reasons, i.e. different hardware info returned from WMI--if Wine even supports it, HKLM\SOFTWARE\Microsoft\Cryptography\MachineGuid values will be different, etc.  Since getting qclauncher to work on Linux is non-standard behavior, I've messaged you on IRC of some _possible_ approaches to getting it to work. It would be neat if one of them worked.

> 
> My Linux fetish aside, people who get error 1501 on actual Windows 10 probably won't benefit from this either, if we're simply extracting that profile from BNL, and then QC expects something else for whatever reason?
> 

That's interesting. I haven't heard of non-qclauncher users getting error 1501. Not sure what's going on there.

**Comment by syncore** [comment] 2018-10-25 04:07
Addressed in [v1.06](https://github.com/syncore/qclauncher/releases/tag/v1.06)

**Closed as completed by syncore** 2018-10-25 04:07 UTC
